### ISSUE TITLE
No way to define empty array as default value

### ISSUE THREAD

**Issue by merwok** [Yelp/swagger_spec_validator#102]
Hello!  We had code working with v2.1.0 that got broken recently.

Our spec had two array params (one CSV, one SSV) that are optional on the client side, with a default in the spec so that the server code (which gets parameters automatically validated / transformed according to the swagger spec) can work with a list (empty or not) without needing type checks or none checks everywhere.

Spec: `type: array`, `collectionFormat: csv`, `default: ''`

This used to be transformed into an empty list automatically.  This seemed perfect: clients don’t have to send the param, the lib applies transforms to the default (split on comma or space), the server code always gets a list.

After updating to 2.3.1, `default: ''` fails because it’s not a list, and `default: []` fails because a list does not have a split method.  From a quick search, it seems like the default value should be of the specified type (so list and not string), which I think was done in #95, but then it should be allowed to specify an empty list as default.

Thanks!

**Comment by macisamuele** [comment]
Hello @merwok thanks a lot for reporting this.

Starting from version 2.2.0 swagger-spec-validator ensures that the default values are valid according to the specs (this was done il #82).
In case of `type: array` the default value `''` is not valid as it is not an array, `collectionFormat` defines how the items will represented on _the wire_ and not how the objects should look like in your code.
So I would say that if specs validation fails if `default: ''`.

swagger-spec-validator>=2.2.0 also enhanced validation capabilities.
According to the [swagger specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) in case of `type: array` the attribute `items` is required so also in this case I would say that the tool is doing is job.

My suggestion would be to define your specs as:
```yaml
type: array
collectionFormat: csv
default: []
items:
  type: string  # string is just an example
```

I'm closing this issue, feel free to reopen it if you think that's the case

**Comment by merwok** [comment]
I fully understand and agree with the first part, it makes sense that `default: ''` is rejected, like I said in my OP.

I did not include the full spec for brevity but we do have `items: type: string` in both cases.  `default: []` causes a type error from some part of swagger_spec_validator that tries to split a string.

**Comment by macisamuele** [comment]
Could you publish the whole specs or equivalent specs that are able to trigger the issue? Without having access to the problematic specs it's hard to identify where the issue could be

**Comment by merwok** [comment]
```yaml
        - name: include
          in: query
          type: array
          items:
            type: string
            enum:
              - first
              - second
          collectionFormat: csv
          default: []
```
