### ISSUE TITLE
Fail to parse schema with property name "null"

### ISSUE THREAD

**Issue by yyang08** [Yelp/swagger_spec_validator#142]
I'm validating a schema translated from Jackson JsonNode object (https://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/JsonNode.html). It has a property "null" and it results in an error when parsing the spec:
```
  JsonNode:
    type: "object"
    properties:
      valueNode:
        type: "boolean"
      containerNode:
        type: "boolean"
      ...
      null:            <-- this caused an error in parsing
        type: "boolean"
```
When I run the spec validation I got the following error: `TypeError: '<' not supported between instances of 'NoneType' and 'str'`.

The spec is auto generated from the object so I cannot change the property name. How can I resolve this?
