### ISSUE TITLE
Check for required `type` field.

### ISSUE THREAD

**Issue by wting** [Yelp/swagger_spec_validator#51]
Here's an example response model that's missing a `type` field for `time_created`:
```yaml
  TokenResponse:
    additionalProperties: false
    properties:
      is_foo:
        type: boolean
      time_created:
        description: The creation time of the access token in ISO8601 format.
        # type: string
    required:
    - is_foo
    type: object
```

While the `time_created` field isn't required, when you use the Swagger object fails due to lack of the `type: string` field. This spec currently passes the Swagger validator.
